services:

  image_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - image-service-network

#  image_service:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./images:/app/images
#    networks:
#      - image-service-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://image_db:5432/images_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    depends_on:
#      - image_db

#networks:
#  image-service-network:
#    driver: bridge

volumes:
  db_data: