spring:
  application:
    name: image-service

  datasource:
    url: jdbc:postgresql://image_db:5432/images_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080